# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Valida a compilação via linha de comando pura para evitar timeout"
  lane :check_build do
    # Build para o Target Aluno
    sh "xcodebuild -workspace WebQuiz.xcworkspace -scheme WebQuiz -destination 'generic/platform=iOS Simulator' CODE_SIGNING_ALLOWED=NO build"
    
    # Build para o Target Admin
    sh "xcodebuild -workspace WebQuiz.xcworkspace -scheme WebQuizAdmin -destination 'generic/platform=iOS Simulator' CODE_SIGNING_ALLOWED=NO build"
  end
end