# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Verifica se os dois targets estão compilando corretamente"
  lane :check_build do
  
    run_tests(
      scheme: "WebQuiz",
      device: "iPhone 15", # Um simulador padrão que tem no Bitrise
      build_for_testing: true
    )

    run_tests(
      scheme: "WebQuizAdmin",
      device: "iPhone 15",
      build_for_testing: true
    )
  end

end
