# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Valida a compilação dos targets (Sem rodar testes e sem assinatura)"
  lane :check_build do
    # Compila o Target Aluno para Simulador
    build_app(
      scheme: "WebQuiz",
      destination: "platform=iOS Simulator,name=iPhone 15",
      skip_codesigning: true,
      skip_package_ipa: true
    )

    # Compila o Target Admin para Simulador
    build_app(
      scheme: "WebQuizAdmin",
      destination: "platform=iOS Simulator,name=iPhone 15",
      skip_codesigning: true,
      skip_package_ipa: true
    )
  end

end
